dist: trusty

language: java
before_install:
- chmod +x travis.sh
install: true

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar

script:
  - mvn clean test jacoco:report coveralls:report

  - ./travis.sh

